services:
  postgres:
    image: postgres:15-alpine
    container_name: iish-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rett
      POSTGRES_PASSWORD: rett
      POSTGRES_DB: iish_dev
    volumes:
      - iish-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: iish-redis
    ports:
      - "6379:6379"
    volumes:
      - iish-redis:/data
    restart: unless-stopped

volumes:
  iish-pgdata:
  iish-redis:
