import { anthropic, CLAUDE_MODEL } from './ai';
import type { PatientProfile, MatchBreakdownItem, LLMAssessment } from '@oncovax/shared';

interface BriefInput {
  trialTitle: string;
  nctId: string;
  phase: string | null;
  sponsor: string | null;
  interventionName: string | null;
  interventionType: string | null;
  briefSummary: string | null;
  rawEligibilityText: string | null;
  matchScore: number;
  matchBreakdown: MatchBreakdownItem[];
  llmAssessment?: LLMAssessment;
  potentialBlockers: string[];
  profile: PatientProfile;
  sites?: { facility: string | null; city: string | null; state: string | null }[];
}

const BRIEF_SYSTEM_PROMPT = `You are an expert oncology clinical trial specialist writing a concise brief for a patient's oncologist. The brief should help the oncologist quickly assess whether this clinical trial is worth discussing with their patient.

Write in a professional, clinical tone. Be specific about data points. Do NOT use patient-facing language — this is doctor-to-doctor communication.

Output format (plain text, NOT markdown):

CLINICAL TRIAL BRIEF
====================

TRIAL: [NCT ID] — [Title]
PHASE: [Phase] | SPONSOR: [Sponsor]
INTERVENTION: [Name] ([Type])

PATIENT MATCH SUMMARY
Score: [X]/100
Key factors:
- [2-4 bullet points on strongest match dimensions]

ELIGIBILITY ASSESSMENT
[2-3 sentences on likely eligibility based on available data]

POTENTIAL CONCERNS
- [Specific blockers or data gaps, if any]

MISSING DATA FOR CONFIRMATION
- [Specific tests or information needed]

RECOMMENDED NEXT STEPS
- [1-3 concrete clinical actions]

NEAREST SITES
[If sites provided, list top 2-3]

---
Generated by OncoVax Clinical Trial Matching Platform
This is an AI-assisted preliminary assessment — not a clinical recommendation.

RULES:
- Keep the entire brief under 400 words
- Use the patient's actual clinical data, not generic statements
- If data is missing, say what specific data is needed
- Do not guess or fabricate clinical details
- potentialBlockers and missingInfo from the LLM assessment should be reflected in POTENTIAL CONCERNS and MISSING DATA`;

export async function generateOncologistBrief(input: BriefInput): Promise<string> {
  const breakdownSummary = input.matchBreakdown
    .map((b) => `${b.category}: ${b.status} (${b.score}/100, weight ${b.weight}) — ${b.reason}`)
    .join('\n');

  const sitesText = input.sites && input.sites.length > 0
    ? input.sites
        .slice(0, 5)
        .map((s) => [s.facility, s.city, s.state].filter(Boolean).join(', '))
        .join('\n')
    : 'No site data available';

  const llmText = input.llmAssessment
    ? `LLM Assessment: ${input.llmAssessment.overallAssessment}\nReasoning: ${input.llmAssessment.reasoning}\nBlockers: ${input.llmAssessment.potentialBlockers.join(', ') || 'None identified'}\nMissing info: ${input.llmAssessment.missingInfo.join(', ') || 'None'}\nAction items: ${input.llmAssessment.actionItems.join(', ') || 'None'}`
    : 'No LLM assessment available';

  const userPrompt = `Generate an oncologist brief for this trial match.

TRIAL:
- Title: ${input.trialTitle}
- NCT ID: ${input.nctId}
- Phase: ${input.phase ?? 'Unknown'}
- Sponsor: ${input.sponsor ?? 'Unknown'}
- Intervention: ${input.interventionName ?? 'Unknown'} (${input.interventionType ?? 'Unknown'})
- Summary: ${input.briefSummary ?? 'Not available'}

ELIGIBILITY CRITERIA:
${input.rawEligibilityText ?? 'Not available'}

PATIENT PROFILE:
${JSON.stringify(input.profile, null, 2)}

MATCH BREAKDOWN (score ${input.matchScore}/100):
${breakdownSummary}

POTENTIAL BLOCKERS:
${input.potentialBlockers.length > 0 ? input.potentialBlockers.join('\n') : 'None identified'}

${llmText}

NEAREST TRIAL SITES:
${sitesText}`;

  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 1024,
    system: BRIEF_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  return (message.content[0] as { type: 'text'; text: string }).text;
}
