import { prisma } from '@/lib/db';
import { anthropic, CLAUDE_MODEL } from '@/lib/ai';
import type { RegulatoryDocumentType } from '@oncovax/shared';

const AI_DISCLAIMER = `
══════════════════════════════════════════════════════════════════
⚠️  AI-GENERATED DOCUMENT — NOT A SUBSTITUTE FOR LEGAL OR MEDICAL ADVICE

This document was generated by an artificial intelligence system. It is
intended as a STARTING POINT for discussion with your physician and
regulatory professionals. It has NOT been reviewed by a licensed attorney
or medical professional.

DO NOT submit this document to any regulatory body without thorough
review and approval by a qualified physician and/or regulatory specialist.

Generated by OncoVax AI · Model: ${CLAUDE_MODEL}
══════════════════════════════════════════════════════════════════
`.trim();

interface TemplateConfig {
  type: RegulatoryDocumentType;
  title: string;
  systemPrompt: string;
  userPromptTemplate: string;
}

export const DOCUMENT_TEMPLATES: Record<RegulatoryDocumentType, TemplateConfig> = {
  fda_form_3926: {
    type: 'fda_form_3926',
    title: 'FDA Form 3926 — Individual Patient Expanded Access IND',
    systemPrompt: 'You are a regulatory affairs specialist helping prepare FDA Form 3926 (Individual Patient Expanded Access Investigational New Drug Application). Generate a comprehensive draft based on the patient data provided. Use formal regulatory language appropriate for FDA submission. Include all required sections.',
    userPromptTemplate: `Prepare a draft FDA Form 3926 for the following patient seeking expanded access to a personalized mRNA cancer vaccine:

Patient Information:
{patientData}

Vaccine Blueprint Summary:
{blueprintData}

Physician Information:
{physicianData}

Include all required sections: patient identification, disease information, treatment plan, informed consent reference, and physician attestation. Mark any fields requiring manual completion as [TO BE COMPLETED BY PHYSICIAN].`,
  },

  right_to_try_checklist: {
    type: 'right_to_try_checklist',
    title: 'Right to Try Eligibility Checklist',
    systemPrompt: 'You are a regulatory affairs specialist creating a Right to Try Act compliance checklist. Generate a comprehensive checklist based on federal Right to Try requirements (21 USC §360bbb-0a) and the patient\'s state laws.',
    userPromptTemplate: `Create a Right to Try eligibility and compliance checklist for:

Patient Information:
{patientData}

State of Residence: {stateOfResidence}

Treatment: Personalized mRNA cancer vaccine

Include: eligibility criteria checklist, required documentation, manufacturer contact requirements, physician certification requirements, informed consent requirements, and insurance/liability considerations.`,
  },

  informed_consent: {
    type: 'informed_consent',
    title: 'Informed Consent Document',
    systemPrompt: 'You are a medical ethicist and regulatory specialist drafting an informed consent document for an investigational personalized cancer vaccine. The document must clearly explain risks, benefits, alternatives, and the experimental nature of the treatment in language accessible to a lay person while meeting regulatory requirements.',
    userPromptTemplate: `Draft an informed consent document for administration of a personalized mRNA cancer vaccine:

Patient Information:
{patientData}

Vaccine Blueprint Summary:
{blueprintData}

Regulatory Pathway: {pathway}

Include: purpose of treatment, description of the investigational product, potential risks and side effects, potential benefits, alternatives, voluntary participation, withdrawal rights, privacy protections, and cost responsibilities. Use clear, accessible language (8th grade reading level).`,
  },

  physician_letter: {
    type: 'physician_letter',
    title: 'Physician Letter of Support',
    systemPrompt: 'You are assisting a physician in drafting a letter of medical necessity and support for a patient seeking access to a personalized mRNA cancer vaccine. The letter should be professional, medically detailed, and persuasive.',
    userPromptTemplate: `Draft a physician letter of support for the following patient:

Patient Information:
{patientData}

Treatment History:
{treatmentHistory}

Vaccine Blueprint Summary:
{blueprintData}

Regulatory Pathway: {pathway}

The letter should: establish the physician's credentials (mark as [PHYSICIAN CREDENTIALS]), describe the patient's diagnosis and treatment history, explain why conventional options are exhausted, describe the personalized vaccine and its scientific basis, support the chosen regulatory pathway, and affirm willingness to oversee administration.`,
  },

  ind_application: {
    type: 'ind_application',
    title: 'Investigational New Drug (IND) Application Draft',
    systemPrompt: 'You are a regulatory affairs specialist helping prepare a physician-sponsored IND application for a personalized mRNA cancer vaccine. Generate a comprehensive draft following FDA guidance for IND submissions (21 CFR Part 312).',
    userPromptTemplate: `Prepare a draft physician-sponsored IND application for:

Patient Information:
{patientData}

Vaccine Blueprint Summary:
{blueprintData}

Manufacturing Information:
{manufacturingData}

Physician Information:
{physicianData}

Include draft sections for: cover letter, Form FDA 1571, investigator's brochure summary, clinical protocol synopsis, chemistry/manufacturing/controls (CMC) summary, pharmacology/toxicology summary, and previous human experience (if any). Mark sections requiring additional data as [REQUIRES ADDITIONAL DATA].`,
  },

  irb_protocol: {
    type: 'irb_protocol',
    title: 'IRB Protocol Synopsis',
    systemPrompt: 'You are a clinical research specialist drafting an IRB (Institutional Review Board) protocol synopsis for review of a personalized mRNA cancer vaccine treatment under expanded access or physician IND.',
    userPromptTemplate: `Draft an IRB protocol synopsis for:

Patient Information:
{patientData}

Treatment: Personalized mRNA cancer vaccine
Regulatory Pathway: {pathway}

Vaccine Blueprint Summary:
{blueprintData}

Include: study title, principal investigator (mark as [PI NAME]), background and rationale, objectives, study design, subject selection, treatment plan, safety monitoring, adverse event reporting, data management, and ethical considerations.`,
  },

  manufacturer_request: {
    type: 'manufacturer_request',
    title: 'Manufacturer Supply Request Letter',
    systemPrompt: 'You are helping draft a formal request letter to a contract manufacturing organization (CDMO) for production of a personalized mRNA cancer vaccine. The letter should be professional and include all technical specifications needed for a manufacturing quote.',
    userPromptTemplate: `Draft a manufacturer supply request letter for:

Patient Information (de-identified):
{patientData}

Vaccine Blueprint Specifications:
{blueprintData}

Regulatory Pathway: {pathway}

Include: request purpose, technical specifications (mRNA sequence length, LNP formulation requirements, QC criteria), quantity needed, timeline requirements, regulatory pathway context, GMP requirements, and requested deliverables (quote, timeline, capabilities confirmation).`,
  },

  physician_discussion_guide: {
    type: 'physician_discussion_guide',
    title: 'Physician Discussion Guide',
    systemPrompt: 'You are a patient advocate helping prepare a clear, organized discussion guide for a patient to use when talking with their oncologist about personalized cancer vaccines and regulatory pathways. Use empathetic, clear language.',
    userPromptTemplate: `Create a physician discussion guide for:

Patient Information:
{patientData}

Vaccine Blueprint Summary:
{blueprintData}

Recommended Pathway: {pathway}

Include: conversation opener suggestions, key questions to ask, explanation of the personalized vaccine (in terms the patient can explain), regulatory pathway overview for the physician, next steps the physician would need to take, and a list of documents the physician may need to review or sign.`,
  },
};

export async function generateRegulatoryDocument(
  assessmentId: string,
  documentType: RegulatoryDocumentType,
): Promise<{ id: string; content: string }> {
  // Load assessment with patient and pipeline data
  const assessment = await prisma.regulatoryPathwayAssessment.findUniqueOrThrow({
    where: { id: assessmentId },
    include: {
      patient: {
        select: { id: true, profile: true },
      },
      pipelineJob: {
        select: {
          vaccineBlueprint: true,
          topNeoantigens: true,
          neoantigenCount: true,
          variantCount: true,
          tmb: true,
          hlaGenotype: true,
        },
      },
    },
  });

  const template = DOCUMENT_TEMPLATES[documentType];
  const profile = (assessment.patient.profile as Record<string, unknown>) ?? {};
  const blueprint = assessment.pipelineJob?.vaccineBlueprint as Record<string, unknown> | null;

  // Build template variables
  const patientData = JSON.stringify({
    cancerType: assessment.cancerType ?? profile.cancerType ?? 'Not specified',
    cancerStage: assessment.cancerStage ?? profile.stage ?? 'Not specified',
    priorTreatmentsFailed: assessment.priorTreatmentsFailed ?? 0,
    priorTreatments: profile.priorTreatments ?? [],
    age: profile.age ?? 'Not specified',
    state: assessment.stateOfResidence ?? 'Not specified',
  }, null, 2);

  const blueprintData = blueprint
    ? JSON.stringify(blueprint, null, 2)
    : 'Vaccine blueprint not yet available — mark sections as [PENDING BLUEPRINT]';

  const physicianData = assessment.hasPhysician
    ? JSON.stringify({
        name: assessment.physicianName ?? '[PHYSICIAN NAME]',
        email: assessment.physicianEmail ?? '[PHYSICIAN EMAIL]',
        institution: assessment.physicianInstitution ?? '[INSTITUTION]',
      }, null, 2)
    : 'Physician not yet identified — mark all physician fields as [TO BE DETERMINED]';

  // Fill template
  let userPrompt = template.userPromptTemplate
    .replace('{patientData}', patientData)
    .replace('{blueprintData}', blueprintData)
    .replace('{physicianData}', physicianData)
    .replace('{pathway}', assessment.recommendedPathway ?? 'consultation_needed')
    .replace('{stateOfResidence}', assessment.stateOfResidence ?? 'Not specified')
    .replace('{treatmentHistory}', JSON.stringify(profile.priorTreatments ?? [], null, 2))
    .replace('{manufacturingData}', 'To be determined based on CDMO selection');

  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 4096,
    system: template.systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const generatedContent = (message.content[0] as { type: 'text'; text: string }).text;
  const fullContent = `${AI_DISCLAIMER}\n\n${generatedContent}`;

  // Store in database
  const doc = await prisma.regulatoryDocument.create({
    data: {
      assessmentId,
      documentType,
      title: template.title,
      content: fullContent,
      templateVersion: '1.0',
      modelUsed: CLAUDE_MODEL,
      patientDataSnapshot: {
        patientData: JSON.parse(patientData),
        blueprintAvailable: !!blueprint,
        physicianAvailable: assessment.hasPhysician,
        generatedAt: new Date().toISOString(),
      },
      status: 'draft',
    },
  });

  return { id: doc.id, content: fullContent };
}
