import { anthropic, CLAUDE_MODEL } from './ai';
import type { PatientProfile, InsuranceCoverageResult } from '@iish/shared';

interface SequencingBriefInput {
  profile: PatientProfile;
  recommendedTests: { testType: string; providerName: string; geneCount: number }[];
  coverageResult: InsuranceCoverageResult;
}

const BRIEF_SYSTEM_PROMPT = `You are an expert oncology genomics specialist writing a concise brief for a patient's oncologist about genomic sequencing options. The brief should help the oncologist decide which test to order and navigate insurance requirements.

Write in a professional, clinical tone. Be specific. This is doctor-to-doctor communication.

Output format (plain text, NOT markdown):

GENOMIC SEQUENCING BRIEF
=========================

PATIENT SUMMARY
[2-3 sentences on relevant clinical details: cancer type, stage, relevant biomarkers, prior treatments]

RECOMMENDED TESTING
[For each recommended test: name, gene count, clinical rationale for this patient]

INSURANCE COVERAGE
[Coverage status, prior auth requirements, CPT codes, key conditions]

CLINICAL RATIONALE
[2-3 sentences on why genomic profiling is indicated per NCCN guidelines for this patient's cancer type and stage]

ACTIONABLE NEXT STEPS
- [1-3 concrete steps: order test, submit prior auth, etc.]

---
Generated by IISH Sequencing Navigation Platform
This is an AI-assisted preliminary assessment — not a clinical recommendation.

RULES:
- Keep the entire brief under 350 words
- Use the patient's actual clinical data
- If data is missing, say what specific data is needed
- Do not fabricate clinical details
- Reference NCCN guidelines where applicable`;

export async function generateSequencingBrief(input: SequencingBriefInput): Promise<string> {
  const { profile, recommendedTests, coverageResult } = input;

  const testsText = recommendedTests
    .map(t => `- ${t.providerName}: ${t.testType.replace(/_/g, ' ')} (${t.geneCount} genes)`)
    .join('\n');

  const userPrompt = `Generate a genomic sequencing brief for this patient.

PATIENT PROFILE:
${JSON.stringify(profile, null, 2)}

RECOMMENDED TESTS:
${testsText}

INSURANCE COVERAGE:
- Insurer: ${coverageResult.insurer}
- Status: ${coverageResult.status}
- Prior auth required: ${coverageResult.priorAuthRequired ? 'Yes' : 'No'}
- CPT codes: ${coverageResult.cptCodes.join(', ') || 'N/A'}
- Conditions: ${coverageResult.conditions.join('; ') || 'None specified'}
- Missing info: ${coverageResult.missingInfo.join(', ') || 'None'}`;

  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 1024,
    system: BRIEF_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  return (message.content[0] as { type: 'text'; text: string }).text;
}
