import { config } from 'dotenv';
import { resolve } from 'path';

// Load env from apps/web/.env
config({ path: resolve(__dirname, '../apps/web/.env') });

import { PrismaClient } from '../packages/db/src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface ProgramSeed {
  name: string;
  organization: string;
  type: string;
  assistanceCategories: string[];
  description: string;
  maxBenefitAmount: number | null;
  benefitDescription: string;
  eligibility: {
    cancerTypes: string[] | 'all';
    insuranceRequired: boolean | null;
    insuranceTypes: string[];
    incomeLimit: { fplPercentage: number | null };
    ageRange: { min: number | null; max: number | null };
    treatmentTypes: string[] | 'all';
    geographicRestrictions: string[];
    citizenshipRequired: boolean;
  };
  status: string;
  applicationProcess: string;
  applicationUrl: string | null;
  applicationPhone: string | null;
  requiredDocuments: string[];
  turnaroundTime: string | null;
  phone: string | null;
  website: string;
  email: string | null;
  hours: string | null;
}

const programs: ProgramSeed[] = [
  // === Copay Foundations (6) ===
  {
    name: 'CancerCare Co-Payment Assistance Foundation',
    organization: 'CancerCare',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment', 'copay_diagnostics'],
    description: 'Helps cancer patients cover copays for chemotherapy, targeted therapy, and related treatments.',
    maxBenefitAmount: 16000,
    benefitDescription: 'Up to $16,000 per year toward treatment copays',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Commercial', 'Medicare'],
      incomeLimit: { fplPercentage: 500 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.cancercare.org/copayfoundation',
    applicationPhone: '1-866-552-6729',
    requiredDocuments: ['Insurance card', 'Treatment plan', 'Income documentation'],
    turnaroundTime: '3-5 business days',
    phone: '1-866-552-6729',
    website: 'https://www.cancercare.org',
    email: 'copay@cancercare.org',
    hours: 'Mon-Fri 9am-7pm ET',
  },
  {
    name: 'HealthWell Foundation',
    organization: 'HealthWell Foundation',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment'],
    description: 'Assists underinsured patients with copays, coinsurance, and premiums for prescribed medications.',
    maxBenefitAmount: 20000,
    benefitDescription: 'Up to $20,000 per year in copay assistance',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Commercial', 'Medicare'],
      incomeLimit: { fplPercentage: 500 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.healthwellfoundation.org',
    applicationPhone: '1-800-675-8416',
    requiredDocuments: ['Insurance card', 'Prescription information', 'Income verification'],
    turnaroundTime: '1-2 business days',
    phone: '1-800-675-8416',
    website: 'https://www.healthwellfoundation.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm ET',
  },
  {
    name: 'Patient Access Network (PAN) Foundation',
    organization: 'PAN Foundation',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment', 'copay_diagnostics'],
    description: 'Helps underinsured patients with out-of-pocket costs for FDA-approved medications.',
    maxBenefitAmount: 15000,
    benefitDescription: 'Up to $15,000 per year in treatment copay assistance',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Commercial', 'Medicare'],
      incomeLimit: { fplPercentage: 400 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.panfoundation.org',
    applicationPhone: '1-866-316-7263',
    requiredDocuments: ['Insurance card', 'Prescription', 'Income documentation'],
    turnaroundTime: '2-3 business days',
    phone: '1-866-316-7263',
    website: 'https://www.panfoundation.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm ET',
  },
  {
    name: 'Good Days',
    organization: 'Good Days (CDF)',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment', 'transportation'],
    description: 'Provides financial assistance for treatment costs and travel to treatment centers.',
    maxBenefitAmount: 12000,
    benefitDescription: 'Up to $12,000 per year in treatment-related assistance',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Commercial', 'Medicare'],
      incomeLimit: { fplPercentage: 500 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.mygooddays.org',
    applicationPhone: '1-877-968-7233',
    requiredDocuments: ['Insurance card', 'Diagnosis confirmation', 'Income verification'],
    turnaroundTime: '3-5 business days',
    phone: '1-877-968-7233',
    website: 'https://www.mygooddays.org',
    email: null,
    hours: 'Mon-Fri 8am-5pm CT',
  },
  {
    name: 'Patient Advocate Foundation Co-Pay Relief',
    organization: 'Patient Advocate Foundation',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment'],
    description: 'Provides direct copay assistance to insured patients who financially and medically qualify.',
    maxBenefitAmount: 14000,
    benefitDescription: 'Up to $14,000 per year in copay relief',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Commercial', 'Medicare'],
      incomeLimit: { fplPercentage: 400 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.copays.org',
    applicationPhone: '1-866-512-3861',
    requiredDocuments: ['Insurance card', 'Treatment plan', 'Household income documentation'],
    turnaroundTime: '3-5 business days',
    phone: '1-866-512-3861',
    website: 'https://www.copays.org',
    email: null,
    hours: 'Mon-Fri 8:30am-5pm ET',
  },
  {
    name: 'The Assistance Fund',
    organization: 'The Assistance Fund',
    type: 'copay_foundation',
    assistanceCategories: ['copay_treatment'],
    description: 'Helps patients afford copays and other out-of-pocket costs for specific disease categories.',
    maxBenefitAmount: 10000,
    benefitDescription: 'Up to $10,000 per year in copay assistance',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: true,
      insuranceTypes: ['Commercial'],
      incomeLimit: { fplPercentage: 500 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'unknown',
    applicationProcess: 'online',
    applicationUrl: 'https://www.theassistancefund.org',
    applicationPhone: '1-855-845-3663',
    requiredDocuments: ['Insurance card', 'Prescription information', 'Proof of income'],
    turnaroundTime: '5-7 business days',
    phone: '1-855-845-3663',
    website: 'https://www.theassistancefund.org',
    email: null,
    hours: 'Mon-Fri 8am-6pm ET',
  },

  // === Breast Cancer-Specific Nonprofits (5) ===
  {
    name: 'Susan G. Komen Financial Assistance',
    organization: 'Susan G. Komen',
    type: 'nonprofit_grant',
    assistanceCategories: ['general_financial', 'copay_treatment', 'transportation', 'living_expenses'],
    description: 'Emergency financial assistance for breast cancer patients in active treatment, covering treatment costs, living expenses, and more.',
    maxBenefitAmount: 5000,
    benefitDescription: 'Up to $5,000 in emergency financial assistance',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: 300 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.komen.org/support-resources/financial-assistance/',
    applicationPhone: '1-877-465-6636',
    requiredDocuments: ['Diagnosis confirmation', 'Treatment plan', 'Income verification', 'Bills or statements'],
    turnaroundTime: '5-10 business days',
    phone: '1-877-465-6636',
    website: 'https://www.komen.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm CT',
  },
  {
    name: 'The Pink Fund',
    organization: 'The Pink Fund',
    type: 'nonprofit_grant',
    assistanceCategories: ['living_expenses'],
    description: 'Provides 90-day non-medical cost-of-living grants for breast cancer patients in active treatment.',
    maxBenefitAmount: 3000,
    benefitDescription: 'Up to $3,000 over 90 days for living expenses',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: 18, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.thepinkfund.org',
    applicationPhone: null,
    requiredDocuments: ['Diagnosis letter', 'Treatment schedule', 'Financial hardship documentation'],
    turnaroundTime: '2-4 weeks',
    phone: '1-877-234-7465',
    website: 'https://www.thepinkfund.org',
    email: 'info@thepinkfund.org',
    hours: null,
  },
  {
    name: 'Sisters Network',
    organization: 'Sisters Network Inc.',
    type: 'nonprofit_grant',
    assistanceCategories: ['general_financial', 'transportation'],
    description: 'Provides financial assistance and support for African American breast cancer survivors.',
    maxBenefitAmount: 2000,
    benefitDescription: 'Financial assistance grants for treatment-related expenses',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'phone',
    applicationUrl: null,
    applicationPhone: '1-866-781-1808',
    requiredDocuments: ['Diagnosis confirmation'],
    turnaroundTime: '1-2 weeks',
    phone: '1-866-781-1808',
    website: 'https://www.sistersnetworkinc.org',
    email: 'info@sistersnetworkinc.org',
    hours: 'Mon-Fri 9am-5pm CT',
  },
  {
    name: 'Young Survival Coalition',
    organization: 'Young Survival Coalition',
    type: 'nonprofit_grant',
    assistanceCategories: ['general_financial', 'fertility_preservation', 'mental_health'],
    description: 'Support for young adults diagnosed with breast cancer, including fertility preservation grants and emergency funding.',
    maxBenefitAmount: 2500,
    benefitDescription: 'Emergency grants and fertility preservation assistance',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: 18, max: 45 },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.youngsurvival.org',
    applicationPhone: null,
    requiredDocuments: ['Diagnosis confirmation', 'Proof of age'],
    turnaroundTime: '1-2 weeks',
    phone: '1-877-972-1011',
    website: 'https://www.youngsurvival.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm ET',
  },
  {
    name: 'BCRF Patient Assistance',
    organization: 'Breast Cancer Research Foundation',
    type: 'nonprofit_grant',
    assistanceCategories: ['general_financial'],
    description: 'Emergency patient assistance fund for breast cancer patients facing financial hardship during treatment.',
    maxBenefitAmount: 1500,
    benefitDescription: 'Emergency grants for treatment-related financial hardship',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'unknown',
    applicationProcess: 'online',
    applicationUrl: 'https://www.bcrf.org',
    applicationPhone: null,
    requiredDocuments: ['Diagnosis confirmation', 'Financial hardship documentation'],
    turnaroundTime: '2-4 weeks',
    phone: '1-866-346-2273',
    website: 'https://www.bcrf.org',
    email: null,
    hours: null,
  },

  // === Pharma Patient Assistance Programs (8) ===
  {
    name: 'Genentech Access Solutions (Herceptin/Perjeta)',
    organization: 'Genentech',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides free Herceptin (trastuzumab) and Perjeta (pertuzumab) for eligible uninsured patients, plus copay assistance for insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free medication for uninsured; copay assistance for insured',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['trastuzumab', 'pertuzumab', 'herceptin', 'perjeta'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.genentech-access.com',
    applicationPhone: '1-866-422-2377',
    requiredDocuments: ['Prescription', 'Insurance status', 'Income documentation (uninsured only)'],
    turnaroundTime: '5-10 business days',
    phone: '1-866-422-2377',
    website: 'https://www.genentech-access.com',
    email: null,
    hours: 'Mon-Fri 6am-5pm PT',
  },
  {
    name: 'Pfizer Oncology Together (Ibrance)',
    organization: 'Pfizer',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Ibrance (palbociclib) at no cost for uninsured patients and copay assistance for eligible insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Ibrance for uninsured; copay cards for insured',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['palbociclib', 'ibrance'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.pfizer.com/patient-assistance',
    applicationPhone: '1-877-744-5675',
    requiredDocuments: ['Prescription', 'Insurance status'],
    turnaroundTime: '5-7 business days',
    phone: '1-877-744-5675',
    website: 'https://www.pfizer.com/patient-assistance',
    email: null,
    hours: 'Mon-Fri 9am-8pm ET',
  },
  {
    name: 'Lilly Oncology Patient Support (Verzenio)',
    organization: 'Eli Lilly',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Verzenio (abemaciclib) free for eligible uninsured patients and copay assistance for insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Verzenio for uninsured; copay savings for insured',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['abemaciclib', 'verzenio'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.verzenio.com/savings',
    applicationPhone: '1-800-545-6962',
    requiredDocuments: ['Prescription', 'Insurance information'],
    turnaroundTime: '3-5 business days',
    phone: '1-800-545-6962',
    website: 'https://www.verzenio.com',
    email: null,
    hours: 'Mon-Fri 8am-8pm ET',
  },
  {
    name: 'Merck Access Program (Keytruda)',
    organization: 'Merck',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Keytruda (pembrolizumab) free for eligible uninsured patients and copay help for those with insurance.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Keytruda for uninsured; copay assistance for insured',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['pembrolizumab', 'keytruda'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.merckhelps.com',
    applicationPhone: '1-855-257-3932',
    requiredDocuments: ['Prescription', 'Insurance details', 'Financial information (uninsured)'],
    turnaroundTime: '5-10 business days',
    phone: '1-855-257-3932',
    website: 'https://www.merckhelps.com',
    email: null,
    hours: 'Mon-Fri 8am-8pm ET',
  },
  {
    name: 'AstraZeneca Patient Support (Lynparza)',
    organization: 'AstraZeneca',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Lynparza (olaparib) at no cost for eligible uninsured patients and copay assistance for insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Lynparza for uninsured; copay assistance for insured',
    eligibility: {
      cancerTypes: ['breast', 'ovarian'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['olaparib', 'lynparza'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.myaccessforoncology.com',
    applicationPhone: '1-844-275-2360',
    requiredDocuments: ['Prescription', 'Insurance information'],
    turnaroundTime: '5-7 business days',
    phone: '1-844-275-2360',
    website: 'https://www.myaccessforoncology.com',
    email: null,
    hours: 'Mon-Fri 8am-6pm ET',
  },
  {
    name: 'Daiichi Sankyo Patient Support (Enhertu)',
    organization: 'Daiichi Sankyo',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Enhertu (trastuzumab deruxtecan) at no cost for eligible uninsured patients and copay support for insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Enhertu for uninsured; copay assistance for insured',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['trastuzumab deruxtecan', 'enhertu', 't-dxd'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.dsi.com/patient-support',
    applicationPhone: '1-833-364-3788',
    requiredDocuments: ['Prescription', 'Insurance information'],
    turnaroundTime: '5-7 business days',
    phone: '1-833-364-3788',
    website: 'https://www.dsi.com/patient-support',
    email: null,
    hours: 'Mon-Fri 8am-8pm ET',
  },
  {
    name: 'Novartis Patient Assistance (Kisqali)',
    organization: 'Novartis',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Kisqali (ribociclib) free for eligible uninsured patients and copay assistance for insured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free Kisqali for uninsured; copay savings for insured',
    eligibility: {
      cancerTypes: ['breast'],
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['ribociclib', 'kisqali'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.novartis.com/patient-assistance',
    applicationPhone: '1-800-277-2254',
    requiredDocuments: ['Prescription', 'Insurance status', 'Income documentation (uninsured)'],
    turnaroundTime: '5-7 business days',
    phone: '1-800-277-2254',
    website: 'https://www.novartis.com/patient-assistance',
    email: null,
    hours: 'Mon-Fri 8am-8pm ET',
  },
  {
    name: 'Bristol-Myers Squibb Patient Assistance (Opdivo/Yervoy)',
    organization: 'Bristol-Myers Squibb',
    type: 'pharma_pap',
    assistanceCategories: ['free_medication', 'copay_treatment'],
    description: 'Provides Opdivo (nivolumab) and Yervoy (ipilimumab) at no cost for eligible uninsured patients.',
    maxBenefitAmount: null,
    benefitDescription: 'Free medication for uninsured; copay assistance for insured',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: ['nivolumab', 'opdivo', 'ipilimumab', 'yervoy'],
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.bmsaccesssupport.com',
    applicationPhone: '1-800-861-0048',
    requiredDocuments: ['Prescription', 'Insurance status'],
    turnaroundTime: '5-10 business days',
    phone: '1-800-861-0048',
    website: 'https://www.bmsaccesssupport.com',
    email: null,
    hours: 'Mon-Fri 8am-8pm ET',
  },

  // === Practical Assistance (6) ===
  {
    name: 'ACS Hope Lodge',
    organization: 'American Cancer Society',
    type: 'lodging_program',
    assistanceCategories: ['lodging'],
    description: 'Free lodging for cancer patients and caregivers who need to travel for treatment. Available in 30+ cities across the US.',
    maxBenefitAmount: null,
    benefitDescription: 'Free lodging during treatment (saves $200+/night)',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: 18, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'phone',
    applicationUrl: null,
    applicationPhone: '1-800-227-2345',
    requiredDocuments: ['Referral from treatment center'],
    turnaroundTime: 'Subject to availability',
    phone: '1-800-227-2345',
    website: 'https://www.cancer.org/treatment/support-programs-and-services/patient-lodging/hope-lodge.html',
    email: null,
    hours: '24/7',
  },
  {
    name: 'ACS Road to Recovery',
    organization: 'American Cancer Society',
    type: 'transportation_program',
    assistanceCategories: ['transportation'],
    description: 'Free rides to and from cancer treatment through trained volunteer drivers.',
    maxBenefitAmount: null,
    benefitDescription: 'Free transportation to/from treatment appointments',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'phone',
    applicationUrl: null,
    applicationPhone: '1-800-227-2345',
    requiredDocuments: [],
    turnaroundTime: '48-hour advance notice',
    phone: '1-800-227-2345',
    website: 'https://www.cancer.org/treatment/support-programs-and-services/road-to-recovery.html',
    email: null,
    hours: '24/7',
  },
  {
    name: 'Angel Flight',
    organization: 'Angel Flight America',
    type: 'transportation_program',
    assistanceCategories: ['transportation'],
    description: 'Free flights for cancer patients who need to travel long distances for treatment.',
    maxBenefitAmount: null,
    benefitDescription: 'Free air transportation to treatment centers',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.angelflightamerica.org',
    applicationPhone: null,
    requiredDocuments: ['Medical referral', 'Treatment appointment confirmation'],
    turnaroundTime: '1-2 weeks',
    phone: null,
    website: 'https://www.angelflightamerica.org',
    email: null,
    hours: null,
  },
  {
    name: 'Family Reach',
    organization: 'Family Reach',
    type: 'nonprofit_grant',
    assistanceCategories: ['living_expenses', 'food', 'general_financial'],
    description: 'Emergency grants to help cancer families cover essential living expenses like rent, utilities, and food.',
    maxBenefitAmount: 5000,
    benefitDescription: 'Up to $5,000 in emergency grants for essential expenses',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.familyreach.org/financial-assistance',
    applicationPhone: null,
    requiredDocuments: ['Diagnosis confirmation', 'Financial hardship documentation'],
    turnaroundTime: '1-2 weeks',
    phone: '1-973-394-1411',
    website: 'https://www.familyreach.org',
    email: 'info@familyreach.org',
    hours: 'Mon-Fri 9am-5pm ET',
  },
  {
    name: 'Meals on Wheels',
    organization: 'Meals on Wheels America',
    type: 'general_assistance',
    assistanceCategories: ['food'],
    description: 'Delivers nutritious meals to homebound individuals, including cancer patients who are unable to prepare food.',
    maxBenefitAmount: null,
    benefitDescription: 'Daily meal delivery during treatment',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'phone',
    applicationUrl: null,
    applicationPhone: '1-888-998-6325',
    requiredDocuments: [],
    turnaroundTime: 'Varies by location',
    phone: '1-888-998-6325',
    website: 'https://www.mealsonwheelsamerica.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm local time',
  },
  {
    name: 'Ronald McDonald House Charities',
    organization: 'Ronald McDonald House Charities',
    type: 'lodging_program',
    assistanceCategories: ['lodging'],
    description: 'Free or low-cost lodging near hospitals for families with children receiving cancer treatment.',
    maxBenefitAmount: null,
    benefitDescription: 'Free or low-cost lodging near treatment centers',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: 21 },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: false,
    },
    status: 'open',
    applicationProcess: 'phone',
    applicationUrl: null,
    applicationPhone: null,
    requiredDocuments: ['Referral from hospital social worker'],
    turnaroundTime: 'Subject to availability',
    phone: '1-630-623-7048',
    website: 'https://www.rmhc.org',
    email: null,
    hours: 'Mon-Fri 9am-5pm CT',
  },

  // === Government Programs (5) ===
  {
    name: 'Medicaid',
    organization: 'Centers for Medicare & Medicaid Services',
    type: 'government_program',
    assistanceCategories: ['copay_treatment', 'copay_diagnostics', 'general_financial'],
    description: 'Federal-state health insurance program for low-income individuals. Many cancer patients qualify, especially after losing employment.',
    maxBenefitAmount: null,
    benefitDescription: 'Comprehensive health coverage including cancer treatment',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: false,
      insuranceTypes: ['Uninsured'],
      incomeLimit: { fplPercentage: 138 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.healthcare.gov/medicaid-chip/',
    applicationPhone: '1-800-318-2596',
    requiredDocuments: ['Proof of income', 'Identification', 'Proof of residency'],
    turnaroundTime: '10-45 days',
    phone: '1-800-318-2596',
    website: 'https://www.medicaid.gov',
    email: null,
    hours: '24/7',
  },
  {
    name: 'Medicare Extra Help / Low-Income Subsidy',
    organization: 'Social Security Administration',
    type: 'government_program',
    assistanceCategories: ['copay_treatment', 'free_medication'],
    description: 'Helps Medicare beneficiaries with limited income and resources pay for prescription drug costs.',
    maxBenefitAmount: 5000,
    benefitDescription: 'Saves an average of $5,000/year on prescription costs',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: true,
      insuranceTypes: ['Medicare'],
      incomeLimit: { fplPercentage: 150 },
      ageRange: { min: 65, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.ssa.gov/medicare/part-d-extra-help',
    applicationPhone: '1-800-772-1213',
    requiredDocuments: ['Medicare card', 'Income documentation', 'Asset information'],
    turnaroundTime: '2-4 weeks',
    phone: '1-800-772-1213',
    website: 'https://www.ssa.gov/medicare/part-d-extra-help',
    email: null,
    hours: 'Mon-Fri 8am-7pm local time',
  },
  {
    name: 'Social Security Disability Insurance (SSDI)',
    organization: 'Social Security Administration',
    type: 'government_program',
    assistanceCategories: ['living_expenses', 'general_financial'],
    description: 'Monthly disability benefits for workers who can no longer work due to cancer diagnosis or treatment. Breast cancer patients may qualify under Compassionate Allowances.',
    maxBenefitAmount: null,
    benefitDescription: 'Monthly income replacement (avg. $1,500/month)',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: null },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.ssa.gov/disability/',
    applicationPhone: '1-800-772-1213',
    requiredDocuments: ['Medical records', 'Work history', 'Doctor statement of disability'],
    turnaroundTime: '3-6 months (faster with Compassionate Allowance)',
    phone: '1-800-772-1213',
    website: 'https://www.ssa.gov/disability/',
    email: null,
    hours: 'Mon-Fri 8am-7pm local time',
  },
  {
    name: 'Supplemental Security Income (SSI)',
    organization: 'Social Security Administration',
    type: 'government_program',
    assistanceCategories: ['living_expenses', 'general_financial'],
    description: 'Monthly income for disabled individuals with limited income and resources, regardless of work history.',
    maxBenefitAmount: null,
    benefitDescription: 'Monthly income support (up to ~$943/month)',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: 100 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.ssa.gov/ssi/',
    applicationPhone: '1-800-772-1213',
    requiredDocuments: ['Medical records', 'Financial information', 'Identification'],
    turnaroundTime: '3-6 months',
    phone: '1-800-772-1213',
    website: 'https://www.ssa.gov/ssi/',
    email: null,
    hours: 'Mon-Fri 8am-7pm local time',
  },
  {
    name: 'State Pharmaceutical Assistance Programs (SPAP)',
    organization: 'Various State Governments',
    type: 'government_program',
    assistanceCategories: ['copay_treatment', 'free_medication'],
    description: 'State-run programs that help residents pay for prescription medications. Availability and benefits vary by state.',
    maxBenefitAmount: null,
    benefitDescription: 'State-specific prescription drug cost assistance',
    eligibility: {
      cancerTypes: 'all',
      insuranceRequired: null,
      insuranceTypes: [],
      incomeLimit: { fplPercentage: 300 },
      ageRange: { min: null, max: null },
      treatmentTypes: 'all',
      geographicRestrictions: [],
      citizenshipRequired: true,
    },
    status: 'open',
    applicationProcess: 'online',
    applicationUrl: 'https://www.medicare.gov/pharmaceutical-assistance-program/',
    applicationPhone: null,
    requiredDocuments: ['Proof of residency', 'Income documentation', 'Prescription information'],
    turnaroundTime: 'Varies by state',
    phone: null,
    website: 'https://www.medicare.gov/pharmaceutical-assistance-program/',
    email: null,
    hours: null,
  },
];

async function seed() {
  console.log(`Seeding ${programs.length} financial programs...`);

  for (const program of programs) {
    const existing = await prisma.financialProgram.findFirst({
      where: { name: program.name },
    });
    if (!existing) {
      await prisma.financialProgram.create({ data: program });
      console.log(`  Created: ${program.name}`);
    } else {
      console.log(`  Exists:  ${program.name}`);
    }
  }

  const count = await prisma.financialProgram.count();
  console.log(`\nDone. Total programs in database: ${count}`);
}

seed()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
