import { config } from 'dotenv';
import { resolve } from 'path';

// Load env from apps/web/.env
config({ path: resolve(__dirname, '../apps/web/.env') });

import { PrismaClient } from '../packages/db/src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface SecondOpinionCenterSeed {
  name: string;
  nciDesignation: 'comprehensive' | 'designated';
  city: string;
  state: string;
  latitude: number;
  longitude: number;
  offersVirtual: boolean;
  virtualPlatform: string | null;
  averageWaitDays: number;
  pathologyReReview: boolean;
  phone: string;
  website: string;
  subspecialties: string[];
  acceptsInsurance: string[];
  estimatedCostInsured: string;
  estimatedCostUninsured: string;
  financialAssistance: boolean;
}

const SHARED_FIELDS = {
  subspecialties: ['breast', 'lung', 'colorectal', 'hematologic'],
  acceptsInsurance: ['Medicare', 'Most major plans'],
  estimatedCostInsured: '$100-500 specialist copay',
  estimatedCostUninsured: '$400-1,000',
  financialAssistance: true,
};

const CENTERS: SecondOpinionCenterSeed[] = [
  // === 14 NCI Comprehensive Cancer Centers ===
  {
    name: 'Memorial Sloan Kettering Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'New York',
    state: 'NY',
    latitude: 40.7641,
    longitude: -73.9568,
    offersVirtual: true,
    virtualPlatform: 'Expert Online Second Opinion',
    averageWaitDays: 7,
    pathologyReReview: true,
    phone: '212-639-2000',
    website: 'https://www.mskcc.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Dana-Farber Cancer Institute',
    nciDesignation: 'comprehensive',
    city: 'Boston',
    state: 'MA',
    latitude: 42.3375,
    longitude: -71.1072,
    offersVirtual: true,
    virtualPlatform: 'eConsult',
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '617-632-3000',
    website: 'https://www.dana-farber.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'MD Anderson Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Houston',
    state: 'TX',
    latitude: 29.7075,
    longitude: -95.3975,
    offersVirtual: true,
    virtualPlatform: 'myMDAnderson',
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '877-632-6789',
    website: 'https://www.mdanderson.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Mayo Clinic Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Rochester',
    state: 'MN',
    latitude: 44.0225,
    longitude: -92.4667,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '507-284-2511',
    website: 'https://www.mayoclinic.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Fred Hutchinson Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Seattle',
    state: 'WA',
    latitude: 47.6275,
    longitude: -122.3361,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '206-667-5000',
    website: 'https://www.fredhutch.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Stanford Cancer Institute',
    nciDesignation: 'comprehensive',
    city: 'Stanford',
    state: 'CA',
    latitude: 37.4346,
    longitude: -122.1753,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '650-498-6000',
    website: 'https://cancer.stanford.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'UCSF Helen Diller Family Comprehensive Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'San Francisco',
    state: 'CA',
    latitude: 37.7661,
    longitude: -122.4576,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '415-353-7070',
    website: 'https://cancer.ucsf.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Johns Hopkins Sidney Kimmel Comprehensive Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Baltimore',
    state: 'MD',
    latitude: 39.2965,
    longitude: -76.5925,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '410-955-8964',
    website: 'https://www.hopkinsmedicine.org/kimmel',
    ...SHARED_FIELDS,
  },
  {
    name: 'Robert H. Lurie Comprehensive Cancer Center of Northwestern University',
    nciDesignation: 'comprehensive',
    city: 'Chicago',
    state: 'IL',
    latitude: 41.8942,
    longitude: -87.6171,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '312-695-0990',
    website: 'https://cancer.northwestern.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Penn Abramson Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Philadelphia',
    state: 'PA',
    latitude: 39.9496,
    longitude: -75.1938,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '215-662-4000',
    website: 'https://www.pennmedicine.org/cancer',
    ...SHARED_FIELDS,
  },
  {
    name: 'UCLA Jonsson Comprehensive Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Los Angeles',
    state: 'CA',
    latitude: 34.0666,
    longitude: -118.4461,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '310-825-5268',
    website: 'https://cancer.ucla.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Vanderbilt-Ingram Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Nashville',
    state: 'TN',
    latitude: 36.1413,
    longitude: -86.8022,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '877-936-8422',
    website: 'https://www.vicc.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Moffitt Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Tampa',
    state: 'FL',
    latitude: 28.0583,
    longitude: -82.3985,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '888-663-3488',
    website: 'https://www.moffitt.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'City of Hope Comprehensive Cancer Center',
    nciDesignation: 'comprehensive',
    city: 'Duarte',
    state: 'CA',
    latitude: 34.1306,
    longitude: -117.9767,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: true,
    phone: '800-826-4673',
    website: 'https://www.cityofhope.org',
    ...SHARED_FIELDS,
  },

  // === 16 NCI Designated Cancer Centers ===
  {
    name: 'Duke Cancer Institute',
    nciDesignation: 'designated',
    city: 'Durham',
    state: 'NC',
    latitude: 36.0082,
    longitude: -78.9393,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '888-275-3853',
    website: 'https://www.dukecancerinstitute.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'University of Michigan Rogel Cancer Center',
    nciDesignation: 'designated',
    city: 'Ann Arbor',
    state: 'MI',
    latitude: 42.2847,
    longitude: -83.7313,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '800-865-1125',
    website: 'https://www.rogelcancercenter.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'UW Carbone Cancer Center',
    nciDesignation: 'designated',
    city: 'Madison',
    state: 'WI',
    latitude: 43.0740,
    longitude: -89.4349,
    offersVirtual: false,
    virtualPlatform: null,
    averageWaitDays: 21,
    pathologyReReview: false,
    phone: '608-263-8600',
    website: 'https://www.uwhealth.org/cancer',
    ...SHARED_FIELDS,
  },
  {
    name: 'University of Colorado Cancer Center',
    nciDesignation: 'designated',
    city: 'Aurora',
    state: 'CO',
    latitude: 39.7451,
    longitude: -104.8388,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '720-848-0300',
    website: 'https://www.coloradocancercenter.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Emory Winship Cancer Institute',
    nciDesignation: 'designated',
    city: 'Atlanta',
    state: 'GA',
    latitude: 33.7932,
    longitude: -84.3237,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '888-946-7447',
    website: 'https://winshipcancer.emory.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Ohio State University Comprehensive Cancer Center',
    nciDesignation: 'designated',
    city: 'Columbus',
    state: 'OH',
    latitude: 39.9942,
    longitude: -83.0196,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '614-293-5066',
    website: 'https://cancer.osu.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Roswell Park Comprehensive Cancer Center',
    nciDesignation: 'designated',
    city: 'Buffalo',
    state: 'NY',
    latitude: 42.8986,
    longitude: -78.8459,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '877-275-7724',
    website: 'https://www.roswellpark.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Siteman Cancer Center',
    nciDesignation: 'designated',
    city: 'St. Louis',
    state: 'MO',
    latitude: 38.6357,
    longitude: -90.2640,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '800-600-3606',
    website: 'https://siteman.wustl.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Huntsman Cancer Institute',
    nciDesignation: 'designated',
    city: 'Salt Lake City',
    state: 'UT',
    latitude: 40.7717,
    longitude: -111.8387,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '877-585-0303',
    website: 'https://www.huntsmancancer.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'UNC Lineberger Comprehensive Cancer Center',
    nciDesignation: 'designated',
    city: 'Chapel Hill',
    state: 'NC',
    latitude: 35.9062,
    longitude: -79.0567,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '866-869-1856',
    website: 'https://unclineberger.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Georgetown Lombardi Comprehensive Cancer Center',
    nciDesignation: 'designated',
    city: 'Washington',
    state: 'DC',
    latitude: 38.9110,
    longitude: -77.0758,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '202-444-2223',
    website: 'https://lombardi.georgetown.edu',
    ...SHARED_FIELDS,
  },
  {
    name: 'Yale Cancer Center',
    nciDesignation: 'designated',
    city: 'New Haven',
    state: 'CT',
    latitude: 41.3029,
    longitude: -72.9342,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: false,
    phone: '203-200-4422',
    website: 'https://www.yalecancercenter.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'MUSC Hollings Cancer Center',
    nciDesignation: 'designated',
    city: 'Charleston',
    state: 'SC',
    latitude: 32.7841,
    longitude: -79.9482,
    offersVirtual: false,
    virtualPlatform: null,
    averageWaitDays: 21,
    pathologyReReview: false,
    phone: '843-792-0700',
    website: 'https://hollingscancercenter.org',
    ...SHARED_FIELDS,
  },
  {
    name: 'Sidney Kimmel Cancer Center at Jefferson',
    nciDesignation: 'designated',
    city: 'Philadelphia',
    state: 'PA',
    latitude: 39.9484,
    longitude: -75.1582,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 14,
    pathologyReReview: false,
    phone: '215-955-6000',
    website: 'https://www.jefferson.edu/cancer',
    ...SHARED_FIELDS,
  },
  {
    name: 'Cleveland Clinic Taussig Cancer Center',
    nciDesignation: 'designated',
    city: 'Cleveland',
    state: 'OH',
    latitude: 41.5020,
    longitude: -81.6214,
    offersVirtual: true,
    virtualPlatform: 'MyConsult',
    averageWaitDays: 7,
    pathologyReReview: true,
    phone: '866-223-8100',
    website: 'https://www.clevelandclinic.org/cancer',
    ...SHARED_FIELDS,
  },
  {
    name: 'Mass General Cancer Center',
    nciDesignation: 'designated',
    city: 'Boston',
    state: 'MA',
    latitude: 42.3628,
    longitude: -71.0690,
    offersVirtual: true,
    virtualPlatform: null,
    averageWaitDays: 10,
    pathologyReReview: true,
    phone: '617-724-4800',
    website: 'https://www.massgeneral.org/cancer-center',
    ...SHARED_FIELDS,
  },
];

async function main() {
  console.log('Seeding second opinion centers...');

  // Delete existing
  await prisma.secondOpinionCenter.deleteMany();

  // Create all 30 centers
  for (const center of CENTERS) {
    await prisma.secondOpinionCenter.create({ data: center });
    console.log(`  Created: ${center.name} (${center.city}, ${center.state}) — ${center.nciDesignation}`);
  }

  console.log(`\nSeeded ${CENTERS.length} second opinion centers`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
