/**
 * Seed Palliative Care Providers
 * Run: npx tsx scripts/seed-palliative-providers.ts
 */
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../packages/db/src/generated/prisma';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter } as any);

const PROVIDERS = [
  // Hospital-based palliative care teams
  { name: 'Memorial Sloan Kettering Supportive Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Memorial Sloan Kettering Cancer Center', servicesOffered: ['symptom management', 'pain management', 'psychosocial support', 'goals of care', 'family meetings'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 3, referralRequired: false, lat: 40.7641, lng: -73.9568, address: '1275 York Avenue', city: 'New York', state: 'NY', zipCode: '10065', phone: '212-639-2000', website: 'https://www.mskcc.org' },
  { name: 'Dana-Farber Adult Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Dana-Farber Cancer Institute', servicesOffered: ['symptom management', 'pain management', 'advance care planning', 'spiritual care', 'bereavement'], acceptsInsurance: ['Aetna', 'Cigna', 'Harvard Pilgrim', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 42.3372, lng: -71.1059, address: '450 Brookline Avenue', city: 'Boston', state: 'MA', zipCode: '02215', phone: '617-632-3000', website: 'https://www.dana-farber.org' },
  { name: 'MD Anderson Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'MD Anderson Cancer Center', servicesOffered: ['symptom management', 'pain management', 'integrative medicine', 'goals of care', 'caregiver support'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 4, referralRequired: false, lat: 29.7076, lng: -95.3975, address: '1515 Holcombe Blvd', city: 'Houston', state: 'TX', zipCode: '77030', phone: '713-792-2121', website: 'https://www.mdanderson.org' },
  { name: 'Mayo Clinic Palliative Medicine', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Mayo Clinic', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'advance directives', 'family counseling'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: true, lat: 44.0225, lng: -92.4660, address: '200 First Street SW', city: 'Rochester', state: 'MN', zipCode: '55905', phone: '507-284-2511', website: 'https://www.mayoclinic.org' },
  { name: 'Stanford Palliative Medicine', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Stanford Health Care', servicesOffered: ['symptom management', 'pain management', 'psychosocial support', 'integrative therapies'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 37.4346, lng: -122.1753, address: '300 Pasteur Drive', city: 'Stanford', state: 'CA', zipCode: '94305', phone: '650-498-6000', website: 'https://stanfordhealthcare.org' },
  { name: 'Cleveland Clinic Palliative Medicine', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Cleveland Clinic', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'spiritual care'], acceptsInsurance: ['Aetna', 'Medical Mutual', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 41.5016, lng: -81.6219, address: '9500 Euclid Avenue', city: 'Cleveland', state: 'OH', zipCode: '44195', phone: '216-444-2200', website: 'https://my.clevelandclinic.org' },

  // Outpatient clinics
  { name: 'Four Seasons Compassion for Life', type: 'palliative_team', setting: 'outpatient', affiliatedHospital: null, servicesOffered: ['symptom management', 'pain management', 'advance care planning', 'caregiver support', 'bereavement'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'Medicare', 'Medicaid'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 3, referralRequired: false, lat: 35.2653, lng: -82.6237, address: '571 S Allen Road', city: 'Flat Rock', state: 'NC', zipCode: '28731', phone: '828-692-6178', website: 'https://www.fourseasonscfl.org' },
  { name: 'Capital Caring Health', type: 'palliative_team', setting: 'outpatient', affiliatedHospital: null, servicesOffered: ['symptom management', 'advance care planning', 'pediatric palliative', 'caregiver support'], acceptsInsurance: ['Aetna', 'Cigna', 'BlueCross BlueShield', 'Medicare', 'Medicaid'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 38.8826, lng: -77.1714, address: '2900 Telestar Court', city: 'Falls Church', state: 'VA', zipCode: '22042', phone: '703-538-2065', website: 'https://www.capitalcaring.org' },
  { name: 'UCSF Symptom Management Service', type: 'palliative_team', setting: 'outpatient', affiliatedHospital: 'UCSF Medical Center', servicesOffered: ['symptom management', 'pain management', 'advance care planning', 'psychosocial support'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: true, lat: 37.7631, lng: -122.4576, address: '1600 Divisadero Street', city: 'San Francisco', state: 'CA', zipCode: '94115', phone: '415-353-2987', website: 'https://www.ucsfhealth.org' },
  { name: 'Emory Palliative Care Center', type: 'palliative_team', setting: 'outpatient', affiliatedHospital: 'Emory Healthcare', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'spiritual care'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare', 'Medicaid'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 33.7932, lng: -84.3238, address: '1365 Clifton Road', city: 'Atlanta', state: 'GA', zipCode: '30322', phone: '404-778-5000', website: 'https://www.emoryhealthcare.org' },

  // Home-based programs
  { name: 'VNSNY Palliative Care', type: 'palliative_team', setting: 'home', affiliatedHospital: null, servicesOffered: ['home visits', 'symptom management', 'pain management', 'caregiver training', 'advance care planning'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'Medicare', 'Medicaid'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 3, referralRequired: true, lat: 40.7453, lng: -73.9812, address: '220 East 42nd Street', city: 'New York', state: 'NY', zipCode: '10017', phone: '212-609-1900', website: 'https://www.vnsny.org' },
  { name: 'Resolution Care', type: 'palliative_team', setting: 'home', affiliatedHospital: null, servicesOffered: ['home-based palliative', 'telemedicine', 'symptom management', 'goals of care', 'advance care planning'], acceptsInsurance: ['Medicare', 'Medi-Cal'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 40.7838, lng: -124.1571, address: '2825 F Street', city: 'Eureka', state: 'CA', zipCode: '95501', phone: '707-267-9877', website: 'https://resolutioncare.com' },
  { name: 'Northwestern Home Palliative Care', type: 'palliative_team', setting: 'home', affiliatedHospital: 'Northwestern Medicine', servicesOffered: ['home visits', 'symptom management', 'goals of care', 'caregiver support'], acceptsInsurance: ['BlueCross BlueShield', 'Aetna', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: true, lat: 41.8964, lng: -87.6212, address: '251 E Huron Street', city: 'Chicago', state: 'IL', zipCode: '60611', phone: '312-926-2000', website: 'https://www.nm.org' },

  // Telehealth-only providers
  { name: 'Iris Telehealth — Palliative', type: 'individual', setting: 'telehealth', affiliatedHospital: null, servicesOffered: ['telehealth consultations', 'symptom management', 'goals of care', 'advance care planning'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 2, referralRequired: false, lat: 30.2672, lng: -97.7431, address: null, city: 'Austin', state: 'TX', zipCode: '78701', phone: '888-260-1685', website: 'https://www.iristelehealth.com' },
  { name: 'Turn-Key Health — Palliative Telemedicine', type: 'np', setting: 'telehealth', affiliatedHospital: null, servicesOffered: ['telehealth consultations', 'symptom management', 'medication management', 'advance care planning'], acceptsInsurance: ['Medicare', 'BlueCross BlueShield', 'Cigna'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 3, referralRequired: false, lat: 33.4484, lng: -112.0740, address: null, city: 'Phoenix', state: 'AZ', zipCode: '85004', phone: '800-555-0199', website: 'https://www.turnkeyhealth.com' },

  // Individual practitioners / NPs
  { name: 'Dr. Sarah Chen, MD — Palliative Medicine', type: 'individual', setting: 'outpatient', affiliatedHospital: 'Cedars-Sinai Medical Center', servicesOffered: ['symptom management', 'pain management', 'goals of care'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 10, referralRequired: true, lat: 34.0751, lng: -118.3804, address: '8700 Beverly Blvd', city: 'Los Angeles', state: 'CA', zipCode: '90048', phone: '310-423-3277', website: 'https://www.cedars-sinai.org' },
  { name: 'Dr. James Rivera, MD — Palliative Oncology', type: 'individual', setting: 'outpatient', affiliatedHospital: 'Penn Medicine', servicesOffered: ['palliative oncology', 'symptom management', 'advance care planning', 'pain management'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'Cigna', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 14, referralRequired: true, lat: 39.9496, lng: -75.1937, address: '3400 Spruce Street', city: 'Philadelphia', state: 'PA', zipCode: '19104', phone: '215-662-4000', website: 'https://www.pennmedicine.org' },
  { name: 'Maria Thompson, APRN — Palliative Care NP', type: 'np', setting: 'outpatient', affiliatedHospital: null, servicesOffered: ['symptom management', 'medication management', 'goals of care', 'caregiver support'], acceptsInsurance: ['Medicare', 'Medicaid', 'BlueCross BlueShield'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 36.1627, lng: -86.7816, address: '2301 Vanderbilt Place', city: 'Nashville', state: 'TN', zipCode: '37235', phone: '615-555-0142', website: null },
  { name: 'Lisa Park, LCSW — Palliative Social Worker', type: 'social_worker', setting: 'outpatient', affiliatedHospital: 'UW Medicine', servicesOffered: ['psychosocial support', 'goals of care conversations', 'advance care planning', 'caregiver support', 'bereavement'], acceptsInsurance: ['Premera', 'Regence', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 47.6499, lng: -122.3083, address: '1959 NE Pacific Street', city: 'Seattle', state: 'WA', zipCode: '98195', phone: '206-598-3300', website: 'https://www.uwmedicine.org' },

  // Additional geographic coverage
  { name: 'Moffitt Cancer Center Supportive Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Moffitt Cancer Center', servicesOffered: ['symptom management', 'pain management', 'psychosocial support', 'integrative medicine'], acceptsInsurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'BlueCross BlueShield', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 28.0651, lng: -82.4330, address: '12902 USF Magnolia Drive', city: 'Tampa', state: 'FL', zipCode: '33612', phone: '813-745-4673', website: 'https://www.moffitt.org' },
  { name: 'Fred Hutch Supportive Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Fred Hutchinson Cancer Center', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'advance care planning'], acceptsInsurance: ['Premera', 'Regence', 'Aetna', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 47.6273, lng: -122.3376, address: '1100 Fairview Avenue N', city: 'Seattle', state: 'WA', zipCode: '98109', phone: '206-667-5000', website: 'https://www.fredhutch.org' },
  { name: 'Duke Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Duke University Medical Center', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'family meetings', 'spiritual care'], acceptsInsurance: ['Aetna', 'Cigna', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 36.0086, lng: -78.9399, address: '2301 Erwin Road', city: 'Durham', state: 'NC', zipCode: '27710', phone: '919-684-8111', website: 'https://www.dukehealth.org' },
  { name: 'UCLA Palliative Care Program', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'UCLA Medical Center', servicesOffered: ['symptom management', 'pain management', 'advance care planning', 'integrative medicine'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 34.0660, lng: -118.4460, address: '757 Westwood Plaza', city: 'Los Angeles', state: 'CA', zipCode: '90095', phone: '310-825-9111', website: 'https://www.uclahealth.org' },
  { name: 'Johns Hopkins Palliative Medicine', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Johns Hopkins Hospital', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'spiritual care', 'bereavement'], acceptsInsurance: ['Aetna', 'Cigna', 'CareFirst', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 39.2966, lng: -76.5927, address: '1800 Orleans Street', city: 'Baltimore', state: 'MD', zipCode: '21287', phone: '410-955-5000', website: 'https://www.hopkinsmedicine.org' },
  { name: 'Vanderbilt Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Vanderbilt University Medical Center', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'caregiver support'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'Cigna', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 36.1416, lng: -86.8021, address: '1211 Medical Center Drive', city: 'Nashville', state: 'TN', zipCode: '37232', phone: '615-322-5000', website: 'https://www.vumc.org' },
  { name: 'OHSU Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Oregon Health & Science University', servicesOffered: ['symptom management', 'pain management', 'advance care planning', 'psychosocial support'], acceptsInsurance: ['Providence', 'Moda', 'BlueCross BlueShield', 'UnitedHealthcare', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 45.4993, lng: -122.6855, address: '3181 SW Sam Jackson Park Rd', city: 'Portland', state: 'OR', zipCode: '97239', phone: '503-494-8311', website: 'https://www.ohsu.edu' },
  { name: 'Michigan Medicine Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'University of Michigan Health', servicesOffered: ['symptom management', 'pain management', 'goals of care', 'spiritual care'], acceptsInsurance: ['BlueCross BlueShield', 'Aetna', 'UnitedHealthcare', 'Priority Health', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 7, referralRequired: false, lat: 42.2829, lng: -83.7297, address: '1500 E Medical Center Drive', city: 'Ann Arbor', state: 'MI', zipCode: '48109', phone: '734-936-4000', website: 'https://www.uofmhealth.org' },
  { name: 'Colorado Palliative & Hospice Care', type: 'palliative_team', setting: 'home', affiliatedHospital: null, servicesOffered: ['home-based palliative', 'symptom management', 'goals of care', 'caregiver support', 'bereavement'], acceptsInsurance: ['Anthem', 'Cigna', 'UnitedHealthcare', 'Medicare', 'Medicaid'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 3, referralRequired: false, lat: 39.7392, lng: -104.9903, address: '1000 Englewood Parkway', city: 'Denver', state: 'CO', zipCode: '80110', phone: '303-561-1234', website: null },
  { name: 'Mass General Palliative Care', type: 'palliative_team', setting: 'hospital', affiliatedHospital: 'Massachusetts General Hospital', servicesOffered: ['symptom management', 'pain management', 'psycho-oncology', 'advance care planning', 'spiritual care'], acceptsInsurance: ['Aetna', 'BlueCross BlueShield', 'Harvard Pilgrim', 'Tufts', 'Medicare'], acceptsMedicare: true, offersTelehealth: true, averageWaitDays: 5, referralRequired: false, lat: 42.3632, lng: -71.0686, address: '55 Fruit Street', city: 'Boston', state: 'MA', zipCode: '02114', phone: '617-726-2000', website: 'https://www.massgeneral.org' },
];

async function main() {
  console.log(`Seeding ${PROVIDERS.length} palliative care providers...`);

  for (const provider of PROVIDERS) {
    await prisma.palliativeCareProvider.upsert({
      where: { id: provider.name }, // will fail — use create with check
      create: provider as any,
      update: {},
    }).catch(async () => {
      // upsert by name not possible with UUID PK — just create if not exists
      const existing = await (prisma as any).palliativeCareProvider.findFirst({
        where: { name: provider.name },
      });
      if (!existing) {
        await (prisma as any).palliativeCareProvider.create({ data: provider });
        console.log(`  Created: ${provider.name}`);
      } else {
        console.log(`  Exists: ${provider.name}`);
      }
    });
  }

  const count = await (prisma as any).palliativeCareProvider.count();
  console.log(`\nTotal palliative care providers: ${count}`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1); });
