import { config } from 'dotenv';
import { resolve } from 'path';

// Load env from apps/web/.env
config({ path: resolve(__dirname, '../apps/web/.env') });

import { PrismaClient } from '@oncovax/db/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface FertilityProviderSeed {
  name: string;
  type: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  latitude: number;
  longitude: number;
  servicesOffered: string[];
  oncologyExperience: boolean;
  randomStartProtocol: boolean;
  letrozoleProtocol: boolean;
  weekendAvailability: boolean;
  acceptsInsurance: string[];
  livestrongPartner: boolean;
  phone: string;
  urgentPhone: string | null;
  website: string;
  oncofertilityCoordinator: string | null;
}

const ALL_SERVICES = [
  'egg_freezing',
  'embryo_freezing',
  'ovarian_tissue_cryopreservation',
  'sperm_banking',
  'gnrh_agonist',
  'fertility_counseling',
];

const PROVIDERS: FertilityProviderSeed[] = [
  // === 6 Major Academic Center REI Departments ===
  {
    name: 'UCSF Center for Reproductive Health',
    type: 'academic_rei',
    address: '550 16th Street, 7th Floor',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94158',
    latitude: 37.7631,
    longitude: -122.4586,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
    livestrongPartner: true,
    phone: '555-415-7631',
    urgentPhone: '555-415-7632',
    website: 'https://www.ucsfhealth.org/clinics/center-for-reproductive-health',
    oncofertilityCoordinator: 'Dr. Mitchell Rosen',
  },
  {
    name: 'NYU Langone Fertility Center',
    type: 'academic_rei',
    address: '660 First Avenue, 5th Floor',
    city: 'New York',
    state: 'NY',
    zipCode: '10016',
    latitude: 40.7421,
    longitude: -73.9742,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Oxford'],
    livestrongPartner: true,
    phone: '555-212-7421',
    urgentPhone: '555-212-7422',
    website: 'https://nyulangone.org/locations/fertility-center',
    oncofertilityCoordinator: 'Dr. Jennifer Mersereau',
  },
  {
    name: 'Northwestern Fertility & Reproductive Medicine',
    type: 'academic_rei',
    address: '675 N St Clair Street, Suite 14-200',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60611',
    latitude: 41.8953,
    longitude: -87.6199,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Humana'],
    livestrongPartner: false,
    phone: '555-312-8953',
    urgentPhone: '555-312-8954',
    website: 'https://www.nm.org/conditions-and-care-areas/fertility-and-reproductive-medicine',
    oncofertilityCoordinator: 'Dr. Francesca Duncan',
  },
  {
    name: 'Johns Hopkins Fertility Center',
    type: 'academic_rei',
    address: '10753 Falls Road, Suite 335',
    city: 'Baltimore',
    state: 'MD',
    zipCode: '21093',
    latitude: 39.2966,
    longitude: -76.5933,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'CareFirst'],
    livestrongPartner: true,
    phone: '555-410-2966',
    urgentPhone: '555-410-2967',
    website: 'https://www.hopkinsmedicine.org/gynecology-obstetrics/fertility-center',
    oncofertilityCoordinator: 'Dr. Mindy Christianson',
  },
  {
    name: 'MD Anderson Fertility Preservation Program',
    type: 'academic_rei',
    address: '1515 Holcombe Blvd, Unit 1360',
    city: 'Houston',
    state: 'TX',
    zipCode: '77030',
    latitude: 29.7072,
    longitude: -95.3979,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Humana'],
    livestrongPartner: false,
    phone: '555-713-7072',
    urgentPhone: '555-713-7073',
    website: 'https://www.mdanderson.org/patients-family/diagnosis-treatment/care-centers-clinics/fertility-preservation.html',
    oncofertilityCoordinator: 'Dr. Terri Woodard',
  },
  {
    name: 'Dana-Farber/Brigham Oncofertility Program',
    type: 'academic_rei',
    address: '75 Francis Street',
    city: 'Boston',
    state: 'MA',
    zipCode: '02115',
    latitude: 42.3375,
    longitude: -71.1074,
    servicesOffered: ALL_SERVICES,
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Harvard Pilgrim'],
    livestrongPartner: true,
    phone: '555-617-3375',
    urgentPhone: '555-617-3376',
    website: 'https://www.dana-farber.org/for-patients-and-families/care-and-treatment/support-services-and-amenities/oncofertility-program',
    oncofertilityCoordinator: 'Dr. Ann Partridge',
  },

  // === 12 Livestrong Fertility Partner Clinics ===
  {
    name: 'Shady Grove Fertility',
    type: 'fertility_clinic',
    address: '15001 Shady Grove Road, Suite 400',
    city: 'Rockville',
    state: 'MD',
    zipCode: '20850',
    latitude: 39.0840,
    longitude: -77.1528,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'CareFirst'],
    livestrongPartner: true,
    phone: '555-301-0840',
    urgentPhone: '555-301-0841',
    website: 'https://www.shadygrovefertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'RMA of New York',
    type: 'fertility_clinic',
    address: '635 Madison Avenue, 10th Floor',
    city: 'New York',
    state: 'NY',
    zipCode: '10022',
    latitude: 40.7614,
    longitude: -73.9776,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Oxford'],
    livestrongPartner: true,
    phone: '555-212-7614',
    urgentPhone: null,
    website: 'https://www.rmany.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'CCRM Fertility',
    type: 'fertility_clinic',
    address: '10290 RidgeGate Circle',
    city: 'Lone Tree',
    state: 'CO',
    zipCode: '80124',
    latitude: 39.5501,
    longitude: -104.8739,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare'],
    livestrongPartner: true,
    phone: '555-303-5501',
    urgentPhone: '555-303-5502',
    website: 'https://www.ccrmivf.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Pacific Fertility Center',
    type: 'fertility_clinic',
    address: '55 Francisco Street, Suite 500',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94133',
    latitude: 37.7905,
    longitude: -122.4002,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'Kaiser Permanente'],
    livestrongPartner: true,
    phone: '555-415-7905',
    urgentPhone: null,
    website: 'https://www.pacificfertilitycenter.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Fertility Centers of Illinois',
    type: 'fertility_clinic',
    address: '900 N Michigan Avenue, Suite 1400',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60611',
    latitude: 41.8841,
    longitude: -87.6362,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Humana'],
    livestrongPartner: true,
    phone: '555-312-8841',
    urgentPhone: null,
    website: 'https://www.fcionline.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'ORM Fertility',
    type: 'fertility_clinic',
    address: '2507 NW Lovejoy Street',
    city: 'Portland',
    state: 'OR',
    zipCode: '97210',
    latitude: 45.5144,
    longitude: -122.6823,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: false,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Providence'],
    livestrongPartner: true,
    phone: '555-503-5144',
    urgentPhone: null,
    website: 'https://www.ormfertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Seattle Reproductive Medicine',
    type: 'fertility_clinic',
    address: '1505 Westlake Avenue N, Suite 400',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98109',
    latitude: 47.6167,
    longitude: -122.3214,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'Premera', 'Regence'],
    livestrongPartner: true,
    phone: '555-206-6167',
    urgentPhone: '555-206-6168',
    website: 'https://www.seattlereproductivemedicine.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Emory Reproductive Center',
    type: 'fertility_clinic',
    address: '550 Peachtree Street NE, 18th Floor',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30308',
    latitude: 33.7947,
    longitude: -84.3233,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'ovarian_tissue_cryopreservation', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Ambetter'],
    livestrongPartner: true,
    phone: '555-404-7947',
    urgentPhone: null,
    website: 'https://www.emoryhealthcare.org/centers-programs/reproductive-center',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Texas Fertility Center',
    type: 'fertility_clinic',
    address: '6500 N Mopac Expressway, Building 1, Suite 1200',
    city: 'Austin',
    state: 'TX',
    zipCode: '78731',
    latitude: 30.3950,
    longitude: -97.7337,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: false,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare'],
    livestrongPartner: true,
    phone: '555-512-3950',
    urgentPhone: null,
    website: 'https://www.txfertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Reproductive Medicine Associates of New Jersey',
    type: 'fertility_clinic',
    address: '140 Allen Road',
    city: 'Basking Ridge',
    state: 'NJ',
    zipCode: '07920',
    latitude: 40.7061,
    longitude: -74.5597,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Horizon'],
    livestrongPartner: true,
    phone: '555-908-7061',
    urgentPhone: null,
    website: 'https://www.rmanj.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Boston IVF',
    type: 'fertility_clinic',
    address: '130 Second Avenue',
    city: 'Waltham',
    state: 'MA',
    zipCode: '02451',
    latitude: 42.3908,
    longitude: -71.2357,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Harvard Pilgrim'],
    livestrongPartner: true,
    phone: '555-781-3908',
    urgentPhone: null,
    website: 'https://www.bostonivf.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Kindbody',
    type: 'fertility_clinic',
    address: '5670 Wilshire Blvd, Suite 1200',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90036',
    latitude: 34.0522,
    longitude: -118.2437,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: false,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Anthem'],
    livestrongPartner: true,
    phone: '555-323-0522',
    urgentPhone: null,
    website: 'https://www.kindbody.com',
    oncofertilityCoordinator: null,
  },

  // === 12 Independent Oncofertility-Experienced Clinics ===
  {
    name: 'Oncofertility Clinic of Philadelphia',
    type: 'fertility_clinic',
    address: '834 Chestnut Street, Suite 300',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19107',
    latitude: 39.9530,
    longitude: -75.1634,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'ovarian_tissue_cryopreservation', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Independence Blue Cross'],
    livestrongPartner: false,
    phone: '555-215-9530',
    urgentPhone: '555-215-9531',
    website: 'https://www.oncofertilityphilly.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Midwest Fertility Center',
    type: 'fertility_clinic',
    address: '4333 Main Street, Suite 200',
    city: 'Downers Grove',
    state: 'IL',
    zipCode: '60515',
    latitude: 41.7950,
    longitude: -88.0112,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Humana'],
    livestrongPartner: false,
    phone: '555-630-7950',
    urgentPhone: null,
    website: 'https://www.midwestfertilitycenter.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Virginia Fertility Associates',
    type: 'fertility_clinic',
    address: '7605 Forest Avenue, Suite 206',
    city: 'Richmond',
    state: 'VA',
    zipCode: '23229',
    latitude: 37.5407,
    longitude: -77.4360,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'Anthem'],
    livestrongPartner: false,
    phone: '555-804-5407',
    urgentPhone: null,
    website: 'https://www.vafertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Carolina Fertility Institute',
    type: 'fertility_clinic',
    address: '1920 W Friendly Avenue, Suite 200',
    city: 'Greensboro',
    state: 'NC',
    zipCode: '27403',
    latitude: 36.0726,
    longitude: -79.7920,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: false,
    randomStartProtocol: true,
    letrozoleProtocol: false,
    weekendAvailability: false,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Aetna'],
    livestrongPartner: false,
    phone: '555-336-0726',
    urgentPhone: null,
    website: 'https://www.carolinafertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Arizona Oncofertility',
    type: 'fertility_clinic',
    address: '2222 E Highland Avenue, Suite 400',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85016',
    latitude: 33.4484,
    longitude: -112.0740,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Banner'],
    livestrongPartner: false,
    phone: '555-602-4484',
    urgentPhone: '555-602-4485',
    website: 'https://www.azoncofertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Rocky Mountain Fertility Center',
    type: 'fertility_clinic',
    address: '300 E Hampden Avenue, Suite 400',
    city: 'Denver',
    state: 'CO',
    zipCode: '80113',
    latitude: 39.7392,
    longitude: -104.9903,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Kaiser Permanente'],
    livestrongPartner: false,
    phone: '555-303-7392',
    urgentPhone: null,
    website: 'https://www.rockymountainfertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Minnesota Fertility Clinic',
    type: 'fertility_clinic',
    address: '920 E 28th Street, Suite 100',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55407',
    latitude: 44.9778,
    longitude: -93.2650,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'HealthPartners', 'Medica'],
    livestrongPartner: false,
    phone: '555-612-9778',
    urgentPhone: null,
    website: 'https://www.mnfertilityclinic.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Florida Fertility Institute',
    type: 'fertility_clinic',
    address: '3000 E Fletcher Avenue, Suite 210',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33613',
    latitude: 27.9506,
    longitude: -82.4572,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: false,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Florida Blue'],
    livestrongPartner: false,
    phone: '555-813-9506',
    urgentPhone: null,
    website: 'https://www.floridafertilityinstitute.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Michigan Reproductive Medicine',
    type: 'fertility_clinic',
    address: '475 Market Place, Suite F',
    city: 'Ann Arbor',
    state: 'MI',
    zipCode: '48108',
    latitude: 42.2808,
    longitude: -83.7430,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'ovarian_tissue_cryopreservation', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Priority Health', 'Blue Care Network'],
    livestrongPartner: false,
    phone: '555-734-2808',
    urgentPhone: '555-734-2809',
    website: 'https://www.michiganreproductivemedicine.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Nashville Fertility Center',
    type: 'fertility_clinic',
    address: '2400 Patterson Street, Suite 319',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37203',
    latitude: 36.1627,
    longitude: -86.7816,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: false,
    randomStartProtocol: true,
    letrozoleProtocol: false,
    weekendAvailability: false,
    acceptsInsurance: ['Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Aetna'],
    livestrongPartner: false,
    phone: '555-615-1627',
    urgentPhone: null,
    website: 'https://www.nashvillefertility.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'Ohio Reproductive Medicine',
    type: 'fertility_clinic',
    address: '4830 Knightsbridge Blvd, Suite E',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43214',
    latitude: 39.9612,
    longitude: -82.9988,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'gnrh_agonist', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: true,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'Medical Mutual'],
    livestrongPartner: false,
    phone: '555-614-9612',
    urgentPhone: null,
    website: 'https://www.ohioreproductivemedicine.com',
    oncofertilityCoordinator: null,
  },
  {
    name: 'New England Fertility',
    type: 'fertility_clinic',
    address: '1275 Summer Street, Suite 101',
    city: 'Stamford',
    state: 'CT',
    zipCode: '06905',
    latitude: 41.0534,
    longitude: -73.5387,
    servicesOffered: ['egg_freezing', 'embryo_freezing', 'sperm_banking', 'fertility_counseling'],
    oncologyExperience: true,
    randomStartProtocol: true,
    letrozoleProtocol: true,
    weekendAvailability: false,
    acceptsInsurance: ['Aetna', 'Blue Cross Blue Shield', 'Cigna', 'UnitedHealthcare', 'ConnectiCare'],
    livestrongPartner: false,
    phone: '555-203-0534',
    urgentPhone: null,
    website: 'https://www.newenglandfertility.com',
    oncofertilityCoordinator: null,
  },
];

async function main() {
  console.log('Seeding fertility providers...');

  // Delete existing
  await prisma.fertilityProvider.deleteMany();

  // Create all providers
  for (const provider of PROVIDERS) {
    await prisma.fertilityProvider.create({ data: provider });
    console.log(`  Created: ${provider.name} (${provider.city}, ${provider.state})`);
  }

  console.log(`\nSeeded ${PROVIDERS.length} fertility providers`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
